#!/bin/bash

pokemon_list='[Bulbasaur, Ivysaur, Venusaur, Charmander, Charmeleon]'
#["bulbasaur", "ivysaur", "venusaur", "charmander", "charmeleon"]
cleaned_list=$(echo "$pokemon_list" | sed 's/\[//;s/\]//' | tr -d ' ')
IFS=',' read -r -a cleaned_list <<< "$cleaned_list"

for name in "${cleaned_list[@]}"; do
    name=$(echo "$name" | tr '[:upper:]' '[:lower:]')
    echo "Fetching data for $name..."
    
    pokemon_url=$(curl -s "https://pokeapi.co/api/v2/pokemon?limit=1000" | jq -r '.results[] | select(.name == "'"$name"'") | .url')
    
    if [ -z "$pokemon_url" ]; then
        echo "Pokemon $name not found."
        continue
    fi
    
    echo "URL for the pokemon ${name} is: ${pokemon_url}"

    success=0
    for attempt in {1..3}; do
        if curl -s "${pokemon_url}" -o "${name}.json"; then
           if jq empty "${name}.json" 2>/dev/null; then
                success=1
                break
            else
                echo "Downloaded data for ${name} is not valid JSON. Retrying..."
            fi
        else
            echo "Attempt ${attempt} failed to fetch data for ${name}. Retrying..."
        fi
        sleep 3
    done
    
    if [ $success -eq 1 ]; then
        echo "Data successfully saved to ${name}.json"
    else
        echo "Failed to fetch data for ${name} after 3 attempts."
        continue
    fi
    sleep 3
done